version: '3.5'
services:
  # MySQL Service
  db:
    image: mysql:8
    container_name: sotoya_mysql
    hostname: sotoya_mysql
    restart: always
    ports:
      - "3306:3306"
    networks:
      sotoya-network:
        aliases:
          - sotoya_mysql_network
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sotoya_db
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    command: 
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_general_ci'
    volumes:
      - ./dbdata:/var/lib/mysql
      - ./sql:/root/sql
      - ./mysql/my.cnf:/etc/mysql/my.cnf

  # PHP Service
  app:
    depends_on:
     - db
    links:
     - db:sotoya_mysql
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sotoya
    hostname: sotoya_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: sotoya
      SERVICE_TAGS: dev
    working_dir: /var/www
    networks:
      sotoya-network:
        aliases:
          - sotoya_app_network
    ports:
      - "9000:9000"
    volumes:
       - ./:/var/www
       - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini

# Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/logs/:/var/logs/nginx/
    networks:
      sotoya-network:
        aliases:
          - sotoya_nginx_network

#Docker Networks
networks:
  sotoya-network:
    name: sotoya-network
    driver: bridge

volumes:
  dbdata:
    driver: local
