version: 2.0

jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "a6:b5:5b:07:89:02:48:a0:f7:94:03:67:66:bb:99:58"
      - run: 
          name: Deploy Sotoya server
          command: |
            ssh -oStrictHostKeyChecking=no -v ${SSH_USER}@${SERVER_IP} "cd ${SERVER_SIDE_DIR} && git pull origin master && ./deploy.sh"
workflows:
  version: 2
  deployment:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
